### ISSUE TITLE
[IDEA] using │and ▄ to make the fireworks fly before exploding

### ISSUE THREAD

**Issue by PalanixYT** [maaslalani/confetty#1]
It would look like this:

`		                ▄
				│
				│
				│
				│
				│
				│
				│
				│
				│
				│
				│
				│
				│`

it seems as though Github doesn't connect the lines, but the characters use up the full space so there would be no gaps

I have a screenshot although I had to use Discord for filesharing
[example](https://cdn.discordapp.com/attachments/338354739978829834/873688800180715550/scrn-08-08-00-06-25.png)

**Comment by maaslalani** [comment]
Yep, this is a great idea. I definitely want to do this! And have the fireworks shoot up and explode. And have it explode where ever the user clicks.

Do you have any interest in implementing this? If so go for it! If not, I will implement this soon.

Thanks for the great idea!

**Comment by PalanixYT** [comment]
I sadly cannot implement this, as I have no knowledge of go

**Comment by maaslalani** [comment]
Sounds good! I'll try to implement this then 😄

If you have any more ideas for new simulations let me know as well!

**Comment by MrMelon54** [comment]
I can try and take a look into it

**Comment by maaslalani** [comment]
> I can try and take a look into it

Thanks so much @MrMelon54 ❤️

**Comment by MrMelon54** [comment]
Should I make the explosion the same colour of the shooting part of the firework?

**Comment by maaslalani** [comment]
> Should I make the explosion the same colour of the shooting part of the firework?

Whichever's easier / keeps the code cleaner, I wouldn't mind the shooting part app being white.

**Comment by MrMelon54** [comment]
> Whichever's easier / keeps the code cleaner, I wouldn't mind the shooting part app being white.

do you mean the head or tail of the shooting part

**Comment by maaslalani** [comment]
> > Whichever's easier / keeps the code cleaner, I wouldn't mind the shooting part app being white.
> 
> 
> 
> do you mean the head or tail of the shooting part

I think the tail is okay to be white and when it explodes it can be colourful, the head (before the explosion) is okay to be white as well (but preferably coloured) as long as the explosion is colourful.

**Comment by MrMelon54** [comment]
It could also spawn multiple explosion effects in different colours

**Comment by maaslalani** [comment]
This works now, thanks to @MrMelon54!

https://user-images.githubusercontent.com/42545625/140459074-e7f096fe-9619-4928-bd83-0dc81ac8d4e3.mov
