### ISSUE TITLE
[Feature request] Publish binaries, brew packages, deb and rpm packages :-) 

### ISSUE THREAD

**Issue by kishaningithub** [maaslalani/confetty#12]
This will make is cool confetty highly accessible for everyone :-) 

I use goreleaser for all my go projects to acheive the same

https://goreleaser.com/

Example repo (my repo): https://github.com/kishaningithub/shopify-csv-download/releases

Let me know if you are fine with this,  i can work on a PR for the same :-)

**Comment by maaslalani** [comment]
See #13
