### ISSUE TITLE
[Idea] Add an easy way use this in other cli apps.

### ISSUE THREAD

**Issue by btvoidx** [maaslalani/confetty#5]
For example, a cli app that creates/set-ups something could add confetti/fireworks to it's "done, go have fun" message.

**Comment by CamiloGarciaLaRotta** [comment]
Given that we have access to the binary, a workaround for now is to directly call it. 

```bash
#!/bin/bash

# some code, and then
confetty
```

But +1 to the request, it would be nice not to have to `exec.Command("confetty")` in Go, but rather import the package directly.

**Comment by sheldonhull** [comment]
I'd love to see this so I could do a timed call. This example is fantastics, but I want to put at the end of a CLI task and have it proceed after a couple seconds similar like:

```go
confetti.Start(2,confetti.Confetti, "Winner Winner Chicken Dinner")
confetti.Start(2,Confetti.Fireworks, "Winner Winner Chicken Dinner")
```

Just a general idea, something to spice up the ending notes but make sure I don't have to `ctrl+c` exiting. 

This is such a fun little app. 
My kids think I'm cool now when they come to use my terminal. :grin:

**Comment by maaslalani** [comment]
Closing since I believe https://github.com/maaslalani/confetty/issues/5#issuecomment-961509275 is the correct solution.
